# Generated by Django 4.2.8 on 2024-07-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MOVIES', models.CharField(max_length=255)),
                ('YEAR', models.IntegerField()),
                ('GENRE', models.CharField(max_length=255)),
                ('RATING', models.FloatField()),
                ('ONE_LINE', models.CharField(max_length=255)),
                ('STARS', models.CharField(max_length=255)),
                ('VOTES', models.IntegerField()),
                ('RunTime', models.IntegerField()),
                ('Gross', models.IntegerField()),
            ],
        ),
    ]
